### ISSUE TITLE
Validate claims issuer is included in cluster issuers

### ISSUE THREAD

**Issue by Taction** [wasmCloud/provider-sdk-go#4]
Fix function `validateProviderInvocation`, add check for validating claims issuer is included in cluster issuers.
You should decode the jwt token and then check the cluster issuers in the host data containing the claim issuer.
This is a sub-issue of pull#3, see context [here](https://github.com/wasmCloud/provider-sdk-go/pull/3#discussion_r1067359020)

**Comment by jordan-rash** [comment]
If you haven't started work on this, I'll knock out this week

**Comment by Taction** [comment]
Thanks, I haven't started work on this. I haven't begun to look into how to parse and validate the token.

**Comment by brooksmtownsend** [comment]
The validation for invocations is a little different nowadays, so closing this one out. Happy to elaborate a bit more
